### ISSUE TITLE
TomCat config files

### ISSUE THREAD

**Issue by applepassion4** [galzandani/CS419Project#1]
## When using the latest tomcat, the server is unable to start using the configuration files given

This might be because the configurations given are version based which was not specified

![image](https://user-images.githubusercontent.com/53684246/144687478-c9ebe377-dc13-4772-8f53-1bed095cfd39.png)

**Comment by galzandani** [comment]
This issue doesn't match my code, maybe you got confused with a different project.

**Comment by applepassion4** [comment]
Sorry check it now, I made a mistake before
